name: Build
on: [push, workflow_dispatch]

env:
  IMAGE: ghcr.io/dellelce/perl-base

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mkit Perl 
        run: docker build -t $IMAGE .
      - name: Perl check version
        run: |
              PERL_VERSION=$(docker run --rm $IMAGE  /app/perl/bin/perl -V | awk ' NR == 1 { gsub(/[()]/, ""); print $6"."$8"."$10; } ')
              echo "PERL_VERSION=$PERL_VERSION" >> $GITHUB_ENV
      - name: Add tag & push
        run: docker tag $IMAGE $IMAGE:$PERL_VERSION && docker push $IMAGE:$PERL_VERSION && docker push $IMAGE
